version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: cpp_app
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/stockdb

  db:
    image: postgres:15
    container_name: stock_db
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
