services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: app
    # For terminal:
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./secrets.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/stockdb
    dns: # Some firewall I set blocks internet access so setting dns fixes (need internet for API)
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: timescale/timescaledb:latest-pg15  # Use TimescaleDB with PostgreSQL 15
    container_name: db
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init-timescaledb.sql:/docker-entrypoint-initdb.d/init-timescaledb.sql
    ports:
      - "0.0.0.0:5432:5432"
    restart: always # Make sure DB container comes up again if it goes down
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stockdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
